### ISSUE TITLE
I got some error like

### ISSUE THREAD

**Issue by AnowarCST** [sohelamin/laravel-starter#1]
I got an error like:

```
`{ [Error: Entry module not found: Error: Can't resolve 'buble' in '/var/www/html/laravel-starter'
resolve 'buble' in '/var/www/html/laravel-starter'
  Parsed request is a module
  using description file: /var/www/html/laravel-starter/package.json (relative path: .)
  after using description file: /var/www/html/laravel-starter/package.json (relative path: .)
    resolve as module
      module variation buble-loader
        /var/www/html/node_modules doesn't exist or is not a directory
......
`
```

(file: npm-dubug.log)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'dev' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev @
6 info dev @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec dev script
9 verbose stack Error: @ dev: `gulp watch`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd /var/www/html/laravel-starter
12 error Linux 4.7.4-200.fc24.x86_64
13 error argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run-script" "dev"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error @ dev: `gulp watch`
17 error Exit status 1
18 error Failed at the @ dev script 'gulp watch'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp watch
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by sohelamin** [comment]
Are you using node 4 and npm 2?
If yes then please upgrade to node 5+ and npm 3+ then try again.
I've no issue in my end.

**Comment by AnowarCST** [comment]
you are right
`node --version`
`v4.5.0`
`npm --version`
`2.15.9`
and I think those are stable version. Let me try with upgrade.
